include: "rules/common.smk"


##### Target rules #####


rule all:
    input:
        results_path+"annotated/all.vcf.gz",
        results_path+"qc/multiqc.html",
        results_path+"plots/depths.svg",
        results_path+"plots/allele-freqs.svg",


##### Modules #####


include: "rules/ref.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/filtering.smk"
include: "rules/stats.smk"
include: "rules/qc.smk"
include: "rules/annotation.smk"
